// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicScore, DefaultScoreProps } from "./plasmic/bolao/PlasmicScore";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { state } from "../state-management/app";
import { useSnapshot } from "valtio";
export interface ScoreProps extends DefaultScoreProps {}

function Score_(props: ScoreProps, ref: HTMLElementRefOf<"div">) {
  const matches = useSnapshot(state.matches);
  console.log("dale", "score", matches);
  if (!matches.find(match => match.match_id === props.matchId)) {
    state.matches.push({ match_id: props.matchId! });
  }
  const match = state.matches.find(match => match.match_id === props.matchId)!;
  return <PlasmicScore 
    root={{ ref }} 
    {...props}
    homeScoreInput={{
      value: match.home_score,
      onChange: (e) => match.home_score = +e.target.value
    }}
    awayScoreInput={{
      value: match.away_score,
      onChange: (e) => match.away_score = +e.target.value
    }}
  />;
}

const Score = React.forwardRef(Score_);
export default Score;
