// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";
import GlobalContextsProvider from "../components/plasmic/bolao/PlasmicGlobalContextsProvider";
import { ScreenVariantProvider } from "../components/plasmic/bolao/PlasmicGlobalVariant__Screen";
import { PlasmicRanking } from "../components/plasmic/bolao/PlasmicRanking";
import { useRouter } from "next/router";
import "@plasmicpkgs/antd/dist/antd.css"

function Ranking() {
  return (
    <GlobalContextsProvider>
      <ph.PageParamsProvider
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <PlasmicRanking />
      </ph.PageParamsProvider>
    </GlobalContextsProvider>
  );
}

export default Ranking;
