// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../components/plasmic/bolao/PlasmicGlobalVariant__Screen";
import { PlasmicSignup } from "../components/plasmic/bolao/PlasmicSignup";
import { useRouter } from "next/router";
import { Supabase } from "../components/supabase";
import { state } from "../state-management/app";

function Signup() {
  const [name, setName] = React.useState("");
  const [username, setUsername] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [error, setError] = React.useState<string | false>(false);
  const router = useRouter();
  console.log("dale", state);
  const onSignup = async () => {
    if (!name) {
      setError("Faltou preencher o campo nome");
      return ;
    }
    if (!username) {
      setError("Faltou preencher o campo usuario");
      return ;
    }
    if (!password) {
      setError("Faltou preencher o campo senha");
      return ;
    }
    const newUser = await Supabase.insert("users", {
      name,
      username,
      password
    });
    if (newUser.code === '23505') {
      setError("Já existe esse usuário");
    } else { 
      state.logged_user_id = newUser[0].id;
      router.push("/");
    }
  }

  return (
    <ph.PageParamsProvider
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicSignup
        error={error}
        name={{
          value: name,
          onChange: (e) => setName(e.target.value)
        }}
        username={{
          value: username,
          onChange: (e) => setUsername(e.target.value)
        }}
        password={{
          value: password,
          onChange: (e) => setPassword(e.target.value)
        }}
        signup={{
          onClick: onSignup
        }}
      />
    </ph.PageParamsProvider>
  );
}

export default Signup;
