// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: r6sSLbmSTeVjqGUVythgwH
// Component: 0vArQkaL-y
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import PalpitesComp from "../../PalpitesComp"; // plasmic-import: Kqr_HwzDFT/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_bolao.module.css"; // plasmic-import: r6sSLbmSTeVjqGUVythgwH/projectcss
import sty from "./PlasmicPalpites.module.css"; // plasmic-import: 0vArQkaL-y/css

export type PlasmicPalpites__VariantMembers = {};

export type PlasmicPalpites__VariantsArgs = {};
type VariantPropType = keyof PlasmicPalpites__VariantsArgs;
export const PlasmicPalpites__VariantProps = new Array<VariantPropType>();

export type PlasmicPalpites__ArgsType = {};
type ArgPropType = keyof PlasmicPalpites__ArgsType;
export const PlasmicPalpites__ArgProps = new Array<ArgPropType>();

export type PlasmicPalpites__OverridesType = {
  root?: p.Flex<"div">;
  palpitesComp?: p.Flex<typeof PalpitesComp>;
};

export interface DefaultPalpitesProps {}

function PlasmicPalpites__RenderFunc(props: {
  variants: PlasmicPalpites__VariantsArgs;
  args: PlasmicPalpites__ArgsType;
  overrides: PlasmicPalpites__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <PalpitesComp
            data-plasmic-name={"palpitesComp"}
            data-plasmic-override={overrides.palpitesComp}
            className={classNames("__wab_instance", sty.palpitesComp)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "palpitesComp"],
  palpitesComp: ["palpitesComp"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  palpitesComp: typeof PalpitesComp;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPalpites__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPalpites__VariantsArgs;
    args?: PlasmicPalpites__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPalpites__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPalpites__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPalpites__ArgProps,
          internalVariantPropNames: PlasmicPalpites__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicPalpites__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPalpites";
  } else {
    func.displayName = `PlasmicPalpites.${nodeName}`;
  }
  return func;
}

export const PlasmicPalpites = Object.assign(
  // Top-level PlasmicPalpites renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    palpitesComp: makeNodeComponent("palpitesComp"),

    // Metadata about props expected for PlasmicPalpites
    internalVariantProps: PlasmicPalpites__VariantProps,
    internalArgProps: PlasmicPalpites__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPalpites;
/* prettier-ignore-end */
